ALTER TABLE users
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE questions
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE answers
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE comments
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE tags
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;